let ATTACKER: Sprite = null
let DEFENDER: Sprite = null
controller.player1.onEvent(ControllerEvent.Connected, function () {
    game.splash("SELECT CLASS")
    if (controller.anyButton.isPressed()) {
        game.showLongText("A : ATTACKER", DialogLayout.Top)
        game.showLongText("Down : DEFENDER", DialogLayout.Top)
    }
    if (controller.A.isPressed()) {
        ATTACKER = sprites.create(img`
            .......ff...............
            ....ffff2ff.............
            ..ffeeeef2ff............
            .ffeeeeef22ff...........
            .feeeeffeeeef...........
            .fffffee2222ef..........
            fffe222ffffe2f..........
            ffffffffeeefff..........
            fefe44ebf44eef..........
            .fee4d4bfddef...........
            ..feee4dddee.c..........
            ...f2222eeddeccccccc....
            ...f444e44ddecddddd.....
            ...fffffeeee.ccccc......
            ..ffffffff...c..........
            ..fff..ff...............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `, SpriteKind.Player)
        controller.player1.moveSprite(ATTACKER)
    }
    if (controller.down.isPressed()) {
        DEFENDER = sprites.create(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . f f f f . . . . . . 
            . . . . f f f 2 2 f f f . . . . 
            . . . f f f 2 2 2 2 f f f . . . 
            . . f f f e e e e e e f f f . . 
            . . f e e 2 2 2 2 2 2 e f f . . 
            . f f e 2 f f f f f f 2 e f f . 
            . f f f f f e e e e f f f f f . 
            . . f e f b f 4 4 f b f e f . . 
            . . f e 4 1 f d d f 1 4 e f . . 
            . . e f f f f d d d 4 e f . . . 
            . . f d d d d f 2 2 2 f e f . . 
            . . f b b b b f 2 2 2 f 4 e . . 
            . . f b b b b f 5 4 4 f . . . . 
            . . . f c c f f f f f f . . . . 
            . . . . f f . . . f f f . . . . 
            `, SpriteKind.Player)
        controller.player1.moveSprite(DEFENDER)
    }
})
