namespace SpriteKind {
    export const DEAD = SpriteKind.create()
}
function HP2 (num: number, mySprite: Sprite) {
    if (HP.value == 100) {
        HP.setColor(7, 7, 2)
    }
    if (HP.value == 50) {
        HP.setColor(4, 2, 2)
    }
    if (HP.value == 0) {
        HP.setColor(2, 2, 2)
    }
}
function ApplyDamage (num: number, num2: number, mySprite: Sprite) {
    HP.value = HP.value - Damage
    if (HP.value == 0) {
        sprites.destroy(Attacker)
        Attacker = sprites.create(img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......fd1111111f.......
            ......fdd1111111df......
            ......fddd111111df......
            ......fdddddd111df......
            ......fbddddbfd1df......
            ......fcbbbdcfddbf......
            .......fcbb11111f.......
            ........fffff1b1f.......
            ........fb111cfbf.......
            ........ffb1b1ff........
            ......f.fffbfbf.........
            ......ffffffff..........
            .......fffff............
            ........................
            ........................
            ........................
            ........................
            `, SpriteKind.DEAD)
    }
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    sprites.destroy(ALIEN)
    ApplyDamage(HP.value, Damage, Attacker)
    HP2(1, Attacker)
})
let ALIEN: Sprite = null
let HP: StatusBarSprite = null
let Damage = 0
let Attacker: Sprite = null
Attacker = sprites.create(img`
    ........................
    ....ffffff..............
    ..ffeeeef2f.............
    .ffeeeef222f............
    .feeeffeeeef...cc.......
    .ffffee2222ef.cdc.......
    .fe222ffffe2fcddc.......
    fffffffeeeffcddc........
    ffe44ebf44ecddc.........
    fee4d41fddecdc..........
    .feee4dddedccc..........
    ..ffee44e4dde...........
    ...f222244ee............
    ...f2222e2f.............
    ...f444455f.............
    ....ffffff..............
    .....fff................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
controller.moveSprite(Attacker)
Damage = 1
HP = statusbars.create(20, 4, StatusBarKind.Health)
HP.setLabel("HP")
HP.attachToSprite(Attacker)
HP.value = 100
HP.max = 100
game.onUpdateInterval(5000, function () {
    ALIEN = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . 3 3 3 3 . . . . . . . 
        . . . 3 3 . . . . 3 3 . . . . . 
        . . 3 3 . . . . . . . 3 . . . . 
        3 3 . . . . . . . . . 3 . . . . 
        3 3 . . . . . . . . . . 3 . . . 
        3 3 . . . . . . . . . . . 3 . . 
        . 3 . . . . . . . . . . . 3 . . 
        . 3 . . . . . . . . . . . 3 . . 
        . . 3 . . . . . . . . . . 3 . . 
        . . 3 . . . . . . . . . 3 . . . 
        . . . 3 . . . . . . . 3 . . . . 
        . . . . 3 3 3 3 3 3 3 . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.Enemy)
    ALIEN.follow(Attacker, 10)
    ALIEN.setPosition(0, 0)
})
